vision_node:
  ros__parameters:
    # Device & Model
    yolo_model: "yolov8n.pt"
    device: "auto"   # auto|cuda|cpu

    # Camera & IO
    camera_index: "/dev/video0"
    camera_backend: "v4l2"   # auto|v4l2|gstreamer
    video_fourcc: "MJPG"
    frame_width: 640
    frame_height: 480
    frame_rate: 30.0
    flip_code: -1

    # Topics
    image_topic: "image_raw"
    debug_image_topic: "image_debug"
    target_topic: "detected_target_point"

    # Detection
    target_class_name: "bottle"
    confidence_threshold: 0.5
    persistence_frames_to_acquire: 3
    persistence_frames_to_lose: 5
    publish_rate_hz: 20.0

robot_controller_node:
  ros__parameters:
    # Topics (relative names preferred for namespace-friendliness)
    target_topic: "detected_target_point"
    joint_states_topic: "joint_states"
    target_joint_angles_topic: "target_joint_angles"

    # Image geometry for pixel->world translation
    image_width: 640
    image_height: 480

    # Pixel-to-world scaling (heuristics)
    pixel_to_cartesian_scale_x: 0.0001
    pixel_to_cartesian_scale_y: 0.0001

    # Camera pose vs arm base
    camera_tilt_angle_deg: 30.0
    camera_forward_offset_m: 0.05

    # Gravity compensation gains
    k_gravity_id2: 12.0
    k_gravity_id3: 6.0

    # Joint limits (deg)
    lift_angle_min_deg: 0.0
    lift_angle_max_deg: 130.0
    elbow_angle_min_deg: 0.0
    elbow_angle_max_deg: 110.0
    pan_angle_min_deg: -110.0
    pan_angle_max_deg: 110.0
    wrist_angle_min_deg: -100.0
    wrist_angle_max_deg: 100.0

    # --- PID Control (arm follower) ---
    # NOTE: These are added as a reference and are commented out to
    # avoid undeclared-parameter errors until RobotControllerNode
    # explicitly declares/uses them. Uncomment after the code update.
    # use_pid_control: true

    # # Pan (horizontal) PID gains
    # kp_pan: 0.006
    # ki_pan: 0.0
    # kd_pan: 0.001
    # # Integral clamp for pan (deg-equivalent per controller internal scale)
    # i_pan_min: -5.0
    # i_pan_max:  5.0

    # # Vertical tracking PID gains (acts on pixel Y → IK target)
    # kp_vert: 0.004
    # ki_vert: 0.0
    # kd_vert: 0.0015
    # # Integral clamp for vertical controller
    # i_vert_min: -5.0
    # i_vert_max:  5.0

    # # Per-joint maximum speeds (deg/s) for slew-rate limiting
    # joint_speed_max_deg_s:
    #   pan: 60.0
    #   lift: 45.0
    #   elbow: 45.0
    #   wrist: 90.0

    # --- Safety / Stability (optional) ---
    # dead_zone_px: 8            # ignore small pixel errors near image center
    # no_detection_behavior: 'hold'  # 'hold' or 'home'
    # no_detection_timeout_s: 3.0    # seconds without detection before applying 'home'
