name: pure-python-tests

on:
  pull_request:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pytest numpy
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=${GITHUB_WORKSPACE}/src/robo_pointer_visual" >> $GITHUB_ENV
      - name: Run pure kinematics tests only (select files)
        run: |
          pytest -q \
            src/robo_pointer_visual/test/test_kinematics.py \
            src/robo_pointer_visual/test/test_kinematics_extra.py
